version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
  
  server:
    build:
      dockerfile: dockerfile
      context: .
    command: sh -c "alembic upgrade head && mkdir -p upload/images && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/bookstore
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
